### ISSUE TITLE
Specify multiple modules

### ISSUE THREAD

**Issue by Derkades** [siacentral/sia-docker#1]
How do I specify multiple modules (e.g. renter and host)? I've separating module names by space and by comma, but that didn't work. I suspect it has something to do with the fact that the environment variable is not in quotation marks

**Comment by n8maninger** [comment]
Module names are single letters.

Below is a list of all the modules available.

Gateway (g):
	The gateway maintains a peer to peer connection to the network and
	enables other modules to perform RPC calls on peers.
	The gateway is required by all other modules.
	Example:
		-e SIA_MODULES="g"
Consensus Set (c):
	The consensus set manages everything related to consensus and keeps the
	blockchain in sync with the rest of the network.
	The consensus set requires the gateway.
	Example:
		-e SIA_MODULES="gc"
Transaction Pool (t):
	The transaction pool manages unconfirmed transactions.
	The transaction pool requires the consensus set.
	Example:
		-e SIA_MODULES="gct"
Wallet (w):
	The wallet stores and manages siacoins and siafunds.
	The wallet requires the consensus set and transaction pool.
	Example:
		-e SIA_MODULES="gctw"
Renter (r):
	The renter manages the user's files on the network.
	The renter requires the consensus set, transaction pool, and wallet.
	Example:
		-e SIA_MODULES="gctwr"
Host (h):
	The host provides storage from local disks to the network. The host
	negotiates file contracts with remote renters to earn money for storing
	other users' files.
	The host requires the consensus set, transaction pool, and wallet.
	Example:
		-e SIA_MODULES="gctwh"
Miner (m):
	The miner provides a basic CPU mining implementation as well as an API
	for external miners to use.
	The miner requires the consensus set, transaction pool, and wallet.
	Example:
		-e SIA_MODULES="gctwm"
Explorer (e):
	The explorer provides statistics about the blockchain and can be
	queried for information about specific transactions or other objects on
	the blockchain.
	The explorer requires the consenus set.
	Example:
		-e SIA_MODULES="gce"

**Comment by Derkades** [comment]
oh, that makes sense. Thanks for the extensive reply
