### ISSUE TITLE
Docker images for ARM

### ISSUE THREAD

**Issue by BouweCeunen** [siacentral/sia-docker#2]
Hi, are there docker images available for ARM cpu architectures?

**Comment by n8maninger** [comment]
There are now prebuilt images for arm64 available on Docker Hub. They can be pulled using the same tags.

`docker pull siacentral/sia:latest`
`docker pull siacentral/sia:1.4.7`
`docker pull siacentral/sia:unstable`

<img width="729" alt="Screen Shot 2020-04-13 at 21 09 28" src="https://user-images.githubusercontent.com/5544150/79119436-553b3c80-7dcb-11ea-8668-4599bcd12a60.png">
