### ISSUE TITLE
Siad saying port is in use

### ISSUE THREAD

**Issue by Opalatal** [siacentral/sia-docker#3]
Not sure if you're able to provide any support on this. Tried to get some help from the official Github and had no luck.

Attempting to run on Unraid using Portainer CE and the docker-compose command.

I've checked that nothing else is using port 9980 in netstat.

Getting this error when I SSH into the container.

/ # siac consensus
Synced: No
Height: 5880
Progress (estimated): 1.9%
/ # siad
Sia Daemon v1.5.6
Git Revision 0b253ab18
Loading...
ERROR: listen tcp 127.0.0.1:9980: bind: address already in use
listen tcp 127.0.0.1:9980: bind: address already in use

Any help is appriected. It's not as simple as sycning cause the port to be binded?

**Comment by n8maninger** [comment]
Looks like you're trying to start `siad` twice. You don't need to start `siad` in the container, it runs when you start the container.
