### ISSUE TITLE
Unraid Docker Installation

### ISSUE THREAD

**Issue by Opalatal** [siacentral/sia-docker#4]
Hi again. Sorry to make another issue, just wasn't able to find a reliable way to get back in touch. Thanks for your reply earlier, you have been more helpful than any other resource I was able to find.

I am attempting to install this Docker on my Unraid OS. Upon running this docker the data is being downloaded to my Docker Container.

Typically the docker container just contains the image for the docker and storage is linked to another volume, the issue I encountered as the Sia block was synced it was saving directly to the docker image instead of the storage folder. I haven't got the knowledge on dockers to work this out myself. Are you able to provide any assistance?

Thanks in advance.

**Comment by n8maninger** [comment]
You need to mount a volume to `/sia-data` to keep data outside of the container.

**Comment by Opalatal** [comment]
Thanks again for the reply.
Is this what you are talking about 

> volumes:
      - sia-data:/sia-data
if I change it to
/mnt/user/sia:/sia-data it should mount that folder for the container?

do I also need to make volumes for these listed on the official github?

> SIA_DIR is /sia
SIA_DATA_DIR is /sia-data
SIAD_DATA_DIR is /sia-data

**Comment by n8maninger** [comment]
> if I change it to `/mnt/user/sia:/sia-data` it should mount that folder for the container?
Yes, it will store data at `/mnt/user/sia` even if the container is restarted

> do I also need to make volumes for these listed on the official github?
No, just `/sia-data`. The others are specific to `nebulouslabs/sia` and aren't necessary.

**Comment by Opalatal** [comment]
fantastic thank you so much
